### ISSUE TITLE
Can a component be shared w/o a module wrapper?

### ISSUE THREAD

**Issue by uberspeck** [nsmolenskii/ng-demo-lib#1]
Thank you for sharing this! I've been scouring the web for a solution like this :) One question, Is it possible to share a component only or is the component required to be associated with a module?

**Comment by nsmolenskii** [comment]
@uberspeck, It is based on the distributing sources files. You could think, that library files it's just another source directory inside of your application. Because of that, you could skip modules and keep only components (directives, pipes, services)instead. 

Nevertheless, module system is very powerful and important concept part of angular. Module class does not prevent you to skip usage it and import components directly. But if you don't provide module class at all, it will make usage of components library a bit complicated.

**Comment by uberspeck** [comment]
Understood, thanks for the quick response @nsmolenskii!
